version: '3'

services:
  db:
    image: "postgres"
    container_name: "constructa-db"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=constructa-db
    ports:
      - "5432:5432"
    volumes:
      - /path/to/data:/var/lib/postgresql/data